const profile = [
  ['Name', 'Hagen Böttcher'], ['Profilnamen', 'NanoPizza · DexPizza'], ['Ort', 'Dresden'],
  ['Sprachen', 'Deutsch · Englisch'], ['Schwerpunkt', 'C# · Lua · FiveM · Android']
];
const skills = [
  ['Programmiersprachen', ['C#', 'Lua', 'JavaScript', 'TypeScript', 'HTML', 'CSS']],
  ['Frameworks', ['.NET', 'Jetpack Compose', 'Material 3', 'ND_Core']],
  ['Werkzeuge & Systeme', ['Git', 'GitHub', 'Visual Studio', 'txAdmin', 'Pterodactyl', 'Linux', 'Raspberry Pi', 'OpenCore']]
];
const projects = [
  { name:'eDienstplanReload', status:'In Weiterentwicklung', featured:true, description:'Persönliche Weiterentwicklung einer Dienstplan-App für die Verwaltung und Darstellung von Arbeitszeiten und Dienstplänen mit einem modernen, an One UI orientierten Android-Design.', details:['Oberfläche orientiert an One UI und Android','Dark Mode, Light Mode und eigene Themes','Lokale Speicherung, offline nutzbar'], tech:['Android','Jetpack Compose','Material 3','Offline-Speicherung'] },
  { name:'FiveM Development', status:'Laufende Entwicklung', featured:true, description:'Eigene FiveM-Ressourcen, Scripts und Systeme für Roleplay-Server. Schwerpunkt auf Lua, Server- und Client-Systemen, UI und Framework-Integration.', details:['Eigene HUDs und NUI-Oberflächen','Serverfunktionen und Server-Client-Logik','Integration mit ND_Core'], tech:['Lua','C#','FiveM','FXServer','ND_Core','NUI'] },
  { name:'Diese Website', status:'Aktiv', description:'Meine persönliche Website: statisch gebaut, ohne Tracking, mit Dark und Light Mode und einer zentralen Konfiguration für Inhalte und Metadaten.', details:['Reines HTML, CSS und JavaScript','Eigene Seiten für Impressum, Datenschutz und 404'], tech:['HTML','CSS','JavaScript'] },
  { name:'Weitere Arbeiten', status:'Laufende Entwicklung', description:'Kleinere Arbeiten aus denselben Bereichen: frühere FiveM-Ressourcen, Android-Projekte, Webprojekte, Serverprojekte und Systemoptimierungen.', details:['Serververwaltung mit txAdmin und Pterodactyl','Linux- und Raspberry-Pi-Setups','macOS-Installationen mit OpenCore'], tech:['C#','.NET','Lua','Linux'] }
];
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const badges = items => items.map(item => `<span class="badge">${esc(item)}</span>`).join('');
const header = (home = true) => `<header class="site-nav"><div class="container nav-inner"><a class="brand" href="${home ? '#home' : '../'}" aria-label="Zur Startseite"><span class="logo">HB</span><span>Hagen Böttcher</span></a><nav aria-label="Hauptnavigation"><ul class="nav-links"><li><a href="${home ? '#home' : '../'}">Home</a></li><li><a href="${home ? '#about' : '../#about'}">Über mich</a></li><li><a href="${home ? '#skills' : '../#skills'}">Skills</a></li><li><a href="${home ? '#projects' : '../#projects'}">Projekte</a></li><li><a href="${home ? '#contact' : '../#contact'}">Kontakt</a></li></ul></nav><div class="nav-actions"><button class="icon-button" id="theme-toggle" type="button" aria-label="Farbschema wechseln">◐</button><button class="menu-button" id="menu-toggle" type="button" aria-label="Navigation öffnen">☰</button></div></div></header>`;
const footer = (home = true) => `<footer class="site-footer"><div class="container footer-grid"><div><strong>Hagen Böttcher</strong><p>Developer & Creator aus Dresden.</p><p>© 2026 Hagen Böttcher. Alle Rechte vorbehalten.</p></div><nav aria-label="Footer-Navigation"><span class="mono">Navigation</span><ul><li><a href="${home ? '#about' : '../#about'}">Über mich</a></li><li><a href="${home ? '#projects' : '../#projects'}">Projekte</a></li><li><a href="${home ? '#contact' : '../#contact'}">Kontakt</a></li></ul></nav><nav aria-label="Rechtliches"><span class="mono">Profile & Rechtliches</span><ul><li><a href="https://github.com/Pizzakaufen" target="_blank" rel="noopener">GitHub</a></li><li><a href="https://www.tiktok.com/@PizzakaufenPro" target="_blank" rel="noopener">TikTok</a></li><li><a href="mailto:hagen@con-meo.de">E-Mail</a></li><li><a href="${home ? 'impressum/' : '../impressum/'}">Impressum</a></li><li><a href="${home ? 'datenschutz/' : '../datenschutz/'}">Datenschutz</a></li></ul></nav></div></footer>`;
const sectionHeading = (label, title, text) => `<div class="section-heading"><span class="mono">${label}</span><h2>${title}</h2><p>${text}</p></div>`;
function homePage() {
  return `${header()}<main id="main"><section id="home" class="hero"><div class="container hero-grid"><div class="reveal"><span class="eyebrow">Dresden · Developer & Creator</span><h1>Hallo, ich bin Hagen.</h1><p class="lead">Ich entwickle eigene Anwendungen, Scripts und technische Lösungen von Software in C# über FiveM-Ressourcen in Lua bis zu Android- und Webprojekten.</p><div class="actions"><a class="button primary" href="#projects">Meine Projekte →</a><a class="button" href="#about">Über mich</a></div></div><div class="card profile reveal"><span class="mono">~/profil</span><dl>${profile.map(row => `<div class="profile-row"><dt>${row[0]}</dt><dd>${row[1]}</dd></div>`).join('')}</dl></div></div></section>
<section id="about" class="section"><div class="container"><div class="split"><div>${sectionHeading('01 — Profil','Über mich','Ich bin Hagen und beschäftige mich hauptsächlich mit Softwareentwicklung, Webentwicklung, FiveM und moderner Computertechnik.')}</div><div><p class="muted">Entwickler und Creator mit Schwerpunkt auf C#, Lua, FiveM und eigenen Softwareprojekten. Ich probiere gerne neue Technologien aus und arbeite an eigenen Projekten.</p><p class="muted">Ich entwickle seit mehreren Jahren; C# und Lua gehören zu den Technologien, mit denen ich am längsten arbeite.</p><div class="cards"><article class="card"><h3>Softwareentwicklung</h3><p>Eigene Anwendungen und Tools in C# und .NET, dazu die Optimierung bestehender Software.</p></article><article class="card"><h3>FiveM Development</h3><p>Eigene Ressourcen, Scripts und Systeme in Lua für Roleplay-Server auf Basis von ND_Core.</p></article><article class="card"><h3>Android & Web</h3><p>Dienstplan-App eDienstplanReload mit Jetpack Compose sowie moderne Webprojekte.</p></article><article class="card"><h3>Technik & Systeme</h3><p>PC-Hardware, Linux, Raspberry Pi, Serververwaltung und Systemoptimierung.</p></article></div></div></div><div class="split" style="margin-top:4rem"><div><span class="mono">Werdegang</span><ol class="timeline"><li><strong>Förderschulabschluss</strong><br><span class="muted">Dinglingerschule Dresden</span></li><li><strong>Berufsvorbereitungsjahr</strong><br><span class="muted">Berufsvorbereitung im Anschluss an die Schule.</span></li><li><strong>BBW Leipzig</strong><br><span class="muted">Weiterführende Ausbildung im Berufsbildungswerk Leipzig.</span></li><li><strong>Praktische Erfahrung</strong><br><span class="muted">Unter anderem bei Lloyd’s Café & Bar.</span></li></ol></div><div class="cards"><article class="card"><span class="mono">Interessen</span><div class="badges">${badges(['FiveM & Roleplay','eigene technische Projekte','Computer & Hardware','Android & Samsung','Linux','Webseiten','Systemoptimierung'])}</div></article><article class="card"><span class="mono">Ziele</span><p style="margin-top:1rem">Eigene Software- und Webprojekte weiterentwickeln, neue technische Fähigkeiten aufbauen und professionelle eigene Projekte umsetzen.</p></article></div></div></div></section>
<section id="skills" class="section"><div class="container">${sectionHeading('02 — Stack','Skills','Technologien, mit denen ich regelmäßig arbeite — ohne Prozentbalken, dafür ehrlich sortiert.')}<div class="cards three">${skills.map(group => `<article class="card"><span class="mono">${group[0]}</span><div class="badges">${badges(group[1])}</div></article>`).join('')}</div></div></section>
<section id="projects" class="section"><div class="container">${sectionHeading('03 — Arbeit','Meine Projekte','Eine Auswahl an Dingen, die ich gebaut habe oder gerade baue.')}<div class="cards">${projects.map(project => `<article class="card project ${project.featured ? 'featured' : ''}"><div style="display:flex;justify-content:space-between;gap:1rem"><h3>${project.name}</h3><span class="badge" style="color:var(--accent)">${project.status}</span></div><p>${project.description}</p><ul>${project.details.map(detail => `<li>${detail}</li>`).join('')}</ul><div class="badges">${badges(project.tech)}</div></article>`).join('')}</div></div></section>
<section id="github" class="section"><div class="container"><div class="card"><span class="mono">04 — Open Source</span><div class="split" style="margin-top:1rem"><div><h2>Auf GitHub</h2><p class="muted">Auf GitHub veröffentliche ich Projekte, Scripts und andere Entwicklungen.</p><span class="mono">github.com/Pizzakaufen</span></div><a class="button primary" href="https://github.com/Pizzakaufen" target="_blank" rel="noopener">GitHub öffnen ↗</a></div></div></div></section>
<section id="contact" class="section"><div class="container">${sectionHeading('05 — Kontakt','Kontakt','Du möchtest mich kontaktieren oder mehr über meine Projekte erfahren?')}<div class="contact-grid"><a class="card contact-card" href="https://github.com/Pizzakaufen" target="_blank" rel="noopener"><span class="mono">GitHub</span><strong>Pizzakaufen</strong></a><a class="card contact-card" href="mailto:hagen@con-meo.de"><span class="mono">E-Mail</span><strong>hagen@con-meo.de</strong></a><div class="card contact-card"><span class="mono">Discord</span><strong>Pizzakaufen</strong></div><a class="card contact-card" href="https://www.tiktok.com/@PizzakaufenPro" target="_blank" rel="noopener"><span class="mono">TikTok</span><strong>@PizzakaufenPro</strong></a></div></div></section></main>${footer()}`;
}
function legalPage(kind) {
  const imprint = kind === 'imprint';
  const title = imprint ? 'Impressum' : 'Datenschutzerklärung';
  const intro = imprint ? 'Anbieterkennzeichnung dieser Website nach § 5 DDG.' : 'Diese Website ist eine statische Seite ohne Nutzerkonten, Formulare und ohne Analyse-Tracking.';
  const body = imprint ? `<div class="note">Noch zu ergänzen: Straße, Hausnummer und Postleitzahl. Diese Angaben liegen nicht vor und dürfen nicht geraten werden.</div><section><h2>Angaben gemäß § 5 DDG</h2><address>Hagen Böttcher<br>[STRASSE UND HAUSNUMMER EINTRAGEN]<br>[PLZ EINTRAGEN] Dresden<br>Deutschland</address></section><section><h2>Kontakt</h2><p>E-Mail: <a href="mailto:hagen@con-meo.de">hagen@con-meo.de</a></p></section><section><h2>Haftung für Inhalte und Links</h2><p>Die Inhalte dieser Seiten wurden mit Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann keine Gewähr übernommen werden. Für Inhalte externer Links sind ausschließlich deren Betreiber verantwortlich.</p></section><section><h2>Urheberrecht</h2><p>Die auf dieser Website veröffentlichten Inhalte und Werke unterliegen dem deutschen Urheberrecht.</p></section>` : `<section><h2>Verantwortlicher</h2><p>Hagen Böttcher, [ADRESSE EINTRAGEN], Dresden<br>E-Mail: <a href="mailto:hagen@con-meo.de">hagen@con-meo.de</a></p></section><section><h2>Hosting und Server-Logfiles</h2><p>Diese Website wird bei [HOSTER EINTRAGEN] gehostet. Beim Aufruf werden technisch notwendige Daten verarbeitet: IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Browser und Betriebssystem.</p></section><section><h2>Cookies und Tracking</h2><p>Es werden keine Analyse- oder Tracking-Cookies gesetzt. Einstellungen für Farbschema werden ausschließlich lokal im Browser gespeichert.</p></section><section><h2>Externe Schriftarten</h2><p>Die Schriftarten werden von den Servern der jeweiligen Anbieter geladen. Dabei wird die IP-Adresse an den Anbieter übertragen.</p></section><section><h2>Deine Rechte</h2><p>Du hast das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch.</p></section>`;
  return `${header(false)}<main id="main"><article class="legal"><div class="container legal-copy"><p class="mono"><a href="../">Startseite</a> / ${title}</p><h1>${title}</h1><p class="lead">${intro}</p><div class="legal-body">${body}</div></div></article></main>${footer(false)}`;
}
function notFoundPage() {
  return `${header(false)}<main id="main"><article class="legal"><div class="container legal-copy"><p class="mono">404 — Nicht gefunden</p><h1>Seite nicht gefunden</h1><p class="lead">Diese Seite existiert nicht oder wurde verschoben.</p><div class="actions"><a class="button primary" href="./">Zur Startseite →</a><a class="button" href="./#projects">Projekte ansehen</a></div></div></article></main>${footer(false)}`;
}
function init() {
  const path = location.pathname;
  const root = document.body;
  const isLegal = path.includes('/impressum') || path.includes('/datenschutz');
  const content = path.includes('/datenschutz') ? legalPage('privacy') : path.includes('/impressum') ? legalPage('imprint') : path.endsWith('/404.html') ? notFoundPage() : homePage();
  root.innerHTML = content;
  const saved = localStorage.getItem('theme'); if (saved === 'light') root.classList.add('light');
  document.querySelector('#theme-toggle')?.addEventListener('click', () => { root.classList.toggle('light'); localStorage.setItem('theme', root.classList.contains('light') ? 'light' : 'dark'); });
  const nav = document.querySelector('.site-nav'); const links = document.querySelector('.nav-links');
  document.querySelector('#menu-toggle')?.addEventListener('click', () => links.classList.toggle('open'));
  window.addEventListener('scroll', () => nav.classList.toggle('scrolled', window.scrollY > 16), { passive:true });
  if (!isLegal) { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('reveal'); }), { threshold:.08 }); document.querySelectorAll('.section, .hero').forEach(item => observer.observe(item)); }
}
init();
